### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by AndreaLombax** [WHKnightZ/OpenGL-Load-Model#2]
In the main.h file there are some function and classes defined in the included files: 
#include "../Library/loadpng.h"
#include "../Library/process_image.h"
#include "../Library/gl_texture.h"

But none of them is present in the repo, why?

**Comment by WHKnightZ** [comment]
> In the main.h file there are some function and classes defined in the included files: #include "../Library/loadpng.h" #include "../Library/process_image.h" #include "../Library/gl_texture.h"
> 
> But none of them is present in the repo, why?

Sorry about that, I didn't know how to link repo when I wrote that project :D
The included files are presented in this repo: [WHKnightZ/Library](https://github.com/WHKnightZ/Library)

**Comment by AndreaLombax** [comment]
Thank you so much.
You really did a good work :D
